apiVersion: v1
kind: Template
labels:
  template: apache
metadata:
  annotations:
    description: A basic builder for n~asq's application
    iconClass: icon-shaddowman
    tags: apache
  name: apache
objects:

- kind: ImageStream
  apiVersion: v1
  metadata:
    name: apache

- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes and load balances the application pods
    name: apache
  spec:
    ports:
    - name: https
      port: 8443
      targetPort: 8443
    selector:
      name: apache
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes and load balances the application pods
    name: apache
  spec:
    ports:
    - name: http
      port: 8080
      targetPort: 8080
    selector:
      name: apache


- apiVersion: v1
  id: apache
  kind: Route
  metadata:
    annotations:
      description: Route for apache's HTTPS service.
    labels:
      application: apache
    name: apache
  spec:
    port:
      targetPort: "https"
    to:
      kind: Service
      name: apache
    tls:
      termination: passthrough


- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    name: "apache-build"
  spec:
    runPolicy: "Serial"
    triggers:
    - type: "ConfigChange"
    source:
      type: "Git"
      git:
        uri: "https://github.com/kevensen/apache-container-ocp"
    strategy:
      strategy:
        type: Docker
        dockerStrategy:
    output:
      to:
        kind: "ImageStreamTag"
        name: "apache:latest"

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the application server
    name: apache
  spec:
    replicas: 1
    selector:
      name: apache
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          name: apache
        name: apache
      spec:
        containers:
        - env:
          - name: APACHE_LOGS_DIR
            value: logs
          image: ' '
          name: apache
          ports:
          - containerPort: 443
#          volumeMounts:
#          - name: secret-volume
#            mountPath: /certs
#            readOnly: true
#        volumes:
#        - name: secret-volume
#          secret:
#            secretName: cert-secret
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - apache
        from:
          kind: ImageStreamTag
          name: apache:latest
      type: ImageChange
